auf neue Wahlordnung geändert von Max
HSZemi/fktools pull request #1
Opened 2019-07-03 11:12 UTC by winnerbyhabit

Dinge an die neue Wahlordnung angepasst
außerdem vereinfachte Bedienung durch commands

2019-07-03 17:22 UTC, HSZemi requested changes

2019-07-03 17:22 UTC, HSZemi commented on dokumente/WPAF/TEMPLATE.tex
> +\fi}
Was ist mit `\dontknow`?

2019-07-03 17:22 UTC, HSZemi commented on dokumente/WPAF/TEMPLATE.tex
> +%== n=3: Unbekannt / Unklar, n=4: Nicht zutreffend / Nicht relevant =========
`n=3` ist doppelt; `\dontknow` fehlt oben

2019-07-03 17:22 UTC, HSZemi commented on dokumente/WPAF/TEMPLATE.tex
> +\sym{0} Liste der Wahlhelferinnen und Wahlhelfer
Hinweis: Aufgrund eines Fehlers bei der Neufassung verbietet die FSWO nicht mehr, dass Kandidierende als Wahlhelfende fungieren. Eine Rüge wäre aber dennoch angebracht, falls das auffallen sollte.

2019-07-03 17:22 UTC, HSZemi commented on dokumente/WPAF/TEMPLATE.tex
> +\sym{0} Übernahme Wählendenverzeichnis 19 Tage vor Wahl
Hinweis: Da die *alleinige* Nichteinhaltung dieser Frist keine Auswirkungen auf die Sitzverteilung haben kann, kann sie auch nicht zu einer Ungültigkeit der Wahl führen.

2019-07-03 17:22 UTC, HSZemi commented on dokumente/WPAF/TEMPLATE.tex
> +	\sym{0} Die Wahl des Wahlausschusses durch FSV oder FSR wurde in der Sitzungseinladung mit einem Verweis auf § 26 Abs. 2 FSWO angekündigt
Hinweis: Eine Verletzung dieser Regel kann imo nicht zur Ungültigkeit der Wahl führen, da die Änderung des Wahlverfahrens durch Anwendung der referenzierten Regel – wie allgemein bekannt ist – technisch nicht möglich ist, weshalb der fehlende Verweis sich auch nicht auf die Sitzverteilung ausgewirkt haben kann :nerd_face:

2019-07-03 17:22 UTC, HSZemi commented on dokumente/WPAF/TEMPLATE.tex
> +	\sym{0} Anträge zum Wahlverfahren wurden ordnungsgemäß behandelt
ordnungsgemäß = abgelehnt? :nerd_face:  
Das wäre megalustig, wenn die FK die Wahlwiederholung anordnet, weil jemand erfolgreich § 26 Abs. 2 getriggert hat.

2019-07-03 17:22 UTC, HSZemi commented on dokumente/WPAF/TEMPLATE.tex
> +\sym{0} Kandidierende sind weder Wahlausschussmitglieder noch Wahlhelfende
Die FSWO verbietet (dummerweise) nicht mehr, dass Kandidierende Wahlhelfende sein können (siehe oben). Eine Rüge sollte es dennoch dafür geben. Oder ihr bastelt euch aus heißer Luft anderweitig diesen Ausschlussgrund. Irgendwas von offensichtlicher Verletzung der Integrität der Wahl oder so.

2019-07-04 08:55 UTC, winnerbyhabit commented
max hat jetzt hoffentlich alles gefixt :)

2019-07-04 19:54 UTC, merged

2019-07-04 19:54 UTC, HSZemi commented
Thank you for your contribution.